/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quicksort;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void testQuickSort() {
        // given
        int[] array = {3,9,4,7,5,0,1,6,8,2};

        // when
        int[] resultArray = new App().solution(array);

        // then
        int[] expectedArray = {0,1,2,3,4,5,6,7,8,9};

        assertArrayEquals(expectedArray, resultArray);
    }

}
